### ISSUE TITLE
Thunderdome Deployment adds _V folders as non-hidden folders

### ISSUE THREAD

**Issue by WvDulken** [koechlm/Vault-Thunderdome-Sample#11]
Hello Markus,

Thank you for your great job.

In our company we use Thunderdome for our deployment tasks:
![2023-06-26 12_11_45-Window](https://github.com/koechlm/Vault-Thunderdome-Sample/assets/137778016/2377243f-533e-4cb4-97a9-00ab57ce0e6b)

When we deploy with thunderdome Vault Folders to Vault working folders or custom folder path locations, Thunderdome creates non hidden _V folders. Normally these folders are created by Vault Professional 2023 as hidden working folders:
![2023-06-26 12_10_12-Window](https://github.com/koechlm/Vault-Thunderdome-Sample/assets/137778016/9980e07e-b6ec-421a-86cf-669586e900a3)

After the deployment the user can see this _V folder inside his working area in Inventor, for example when choosing templates:
![2023-06-26 12_18_07-Window](https://github.com/koechlm/Vault-Thunderdome-Sample/assets/137778016/f5656c11-b191-45fb-9867-938289373170)

Can the Thunderdome deployment also make _V folders hidden, or can Thunderdome skip the creation of this folders?

Best Greetings,
William van Dulken
Bosman Van Zaal

**Comment by koechlm** [comment]
Hello William, thank you for this submission and the heads-up on the _V folders. I knew that I needed to delete all _V Folders from the local folder as a deployment creator, but it makes the most sense to enhance Thunderdome not to create this at all. Do you know Inventor template folders synchronize as a default option in Inventor-Vault 2024?

**Comment by WvDulken** [comment]
Hi Markus, 
Thanks for your reply. I did not knew Vault 2024 could do that. Unfortunately we are sticked to 2023 until somewhere next year for our company. What is your advise in this one? Is it possible to enhance Thunderdome 2023 for this issue or does it have to stay a manual task to delete _V folders after update and explain this delete operation to the end users? 
Best greetings, William van Dulken

**Comment by koechlm** [comment]
Hi @WvDulken, The best workaround in 2023 is to turn off the Hidden Folder display before you capture the template files. It is possible to enhance Thunderdome in theory, but I won't be able to schedule time for the foreseeable.
Best regards, Markus

**Comment by WvDulken** [comment]
Hi @koechlm, that sounds like an easy solution/workaround to turn off the Hidden Folder display in Windows. I will try this during the next deployment update. Thanks for the advise! 
Best greetings, William van Dulken

**Comment by WvDulken** [comment]
Hi @koechlm , I tried your work around, to turn off the hidden folder display in windows before building a new deployment. Unfortunately this does not work, we still get non-hidden _V folders at our updated clients. Do you think I missed something?

Best Greetings, William van Dulken

**Comment by koechlm** [comment]
Hi @WvDulken, I reviewed the code and concept of capturing Vault folders; unfortunately, I was wrong: there is no way to exclude the _V folder on the end-user's side. I created an updated version for 2024 that excludes these folders/content.
Best regards,
Markus

**Comment by koechlm** [comment]
Published Update 1 releases for 2023 and 2024 versions: https://github.com/koechlm/Vault-Thunderdome-Sample/releases/tag/2023.1, https://github.com/koechlm/Vault-Thunderdome-Sample/releases/tag/2024.1
