### ISSUE TITLE
Thunderdome Sample 2023

### ISSUE THREAD

**Issue by koechlm** [koechlm/Vault-Thunderdome-Sample#6]

**Comment by BeHo778** [comment]
Hello Markus,

thank you for your great job.

Is it possible to get some options for folder transmitting e.g. 
- delete all folders and files before copy the new one, 
- copy only all new files
- copy all files and force overwritting

Is it possible to include a check prior the distribution of the new deployment if some other programs are running like jobprocessor, inventor and / or autocad mechanical with a abort of the distribution and a warning for closing the running programs?

Or include the Grid settings for e.g. Inventor Vault AddIn?

Kind regards,
Holger

**Comment by koechlm** [comment]
@BeHo778: thank you for the suggestions. I created a new enhancement request for the deployment options. The pre-check for other active clients preventing a complete deployment is already listed with issue #4
